/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
static yyconst short int yy_accept[53] =
    {   0,
        0,    0,   27,   25,    2,   25,   24,   25,   13,   14,
       11,    9,   10,   12,    7,   23,   20,    8,   20,   22,
       22,   22,   22,   22,   18,   25,   19,   21,   16,    7,
       20,   22,   22,   22,   15,   22,   22,   22,   17,   22,
        3,    5,   22,   22,   22,   22,   22,    6,    0,    4,
        1,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    4,    1,    5,    1,    6,
        7,    8,    9,    1,   10,    1,   11,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,   13,   14,
       15,   16,    1,    1,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,   18,    1,   19,   17,   17,   17,

       20,   21,   17,   22,   23,   17,   17,   24,   25,   26,
       27,   17,   17,   28,   17,   29,   17,   17,   30,   17,
       17,   17,   31,   32,   33,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[34] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        1,    1,    1
    } ;

static yyconst short int yy_base[54] =
    {   0,
        0,    0,   61,   62,   62,   45,   62,   54,   62,   62,
       62,   62,   62,   62,   46,   62,   42,   41,   40,    0,
       10,   14,   35,   31,   62,   20,   62,   62,   62,   39,
       62,    0,   23,   21,    0,   19,   24,   23,   62,   26,
        0,    0,   18,   19,   13,   35,   19,    0,   31,    0,
       62,   62,   34
    } ;

static yyconst short int yy_def[54] =
    {   0,
       52,    1,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   53,
       53,   53,   53,   53,   52,   52,   52,   52,   52,   52,
       52,   53,   53,   53,   53,   53,   53,   53,   52,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   52,   53,
       52,    0,   52
    } ;

static yyconst short int yy_nxt[96] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,    4,   20,   20,
       21,   20,   22,   20,   23,   20,   20,   20,   20,   24,
       25,   26,   27,   33,   35,   32,   34,   51,   50,   36,
       49,   48,   47,   46,   45,   44,   43,   42,   41,   40,
       30,   39,   38,   37,   31,   28,   31,   30,   29,   28,
       52,    3,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52

    } ;

static yyconst short int yy_chk[96] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   21,   22,   53,   21,   49,   47,   22,
       46,   45,   44,   43,   40,   38,   37,   36,   34,   33,
       30,   26,   24,   23,   19,   18,   17,   15,    8,    6,
        3,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "testc4.l"
#define INITIAL 0
#line 2 "testc4.l"
  #include<stdlib.h>
  #include<string.h>
  #include<ctype.h>
  void recover(); 
int value();
struct st
{
  char sm[100];
};
struct st symboltable[100]; 
int sttop=-1;

  struct ac
 {
   char sr;
   int srnum;
 }action[100][50];

struct righthand
{
   char rprod[100];
};

struct prod
{
	int len;
	char lhs[100];
	struct righthand rhs[100];
}production[50];

struct sym
{
   char ss[50];
};

int gotor[100][20];

int stacks[100];
struct sym symbols[100];
int stackstop=-1;
int symbolstop=-1;
int k=0;
int ink;
int errors=0;
int lines=1;
int index, index1;

#line 449 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 51 "testc4.l"

#line 602 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 53 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 62 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 52 "testc4.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 53 "testc4.l"
lines++;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 54 "testc4.l"
{return 22;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 55 "testc4.l"
{return 21;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "testc4.l"
{return 2;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "testc4.l"
{return 3;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "testc4.l"
return 6;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 59 "testc4.l"
return 7;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "testc4.l"
return 8;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "testc4.l"
return 9;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "testc4.l"
return 10;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 63 "testc4.l"
return 11;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 64 "testc4.l"
return 12;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 65 "testc4.l"
return 13;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "testc4.l"
return 14;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "testc4.l"
return 15;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "testc4.l"
return 16;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "testc4.l"
return 17;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "testc4.l"
return 18;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "testc4.l"
return 19;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "testc4.l"
return 20;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "testc4.l"
{return value();}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "testc4.l"
return 4;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "testc4.l"
return 5;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "testc4.l"
;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 79 "testc4.l"
ECHO;
	YY_BREAK
#line 815 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 53 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 53 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 52);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 79 "testc4.l"

 
main()
{
gotor[2][0]=52;
gotor[49][6]=31;
gotor[33][6]=31;
//gotor[33][0]=16;

//for loop
gotor[71][4]=15;
gotor[71][0]=72;
gotor[72][5]=16;
gotor[72][4]=15;
gotor[72][0]=73;
gotor[75][5]=77;
gotor[73][8]=78;
gotor[79][4]=15;
gotor[79][0]=80;

//while loop
gotor[62][5]=16;
gotor[64][4]=65;
gotor[64][0]=66;
gotor[1][7]=67;

//equal or not equal
gotor[55][5]=56;

//comparing
gotor[53][5]=54;

//if new
gotor[49][0]=2;
gotor[49][4]=15;
gotor[41][4]=15;
gotor[41][0]=2;
gotor[41][6]=31;
gotor[2][6]=52;

//gotor[37][4]=52;

gotor[35][0]=48;
gotor[48][4]=47;
gotor[49][3]=6;
gotor[49][2]=4;
gotor[49][1]=3;
//start recursion

gotor[2][1]=46;
gotor[2][3]=6;
gotor[2][2]=4;
gotor[2][4]=47;
	
//basic
gotor[1][0]=2;
gotor[1][1]=3;
gotor[1][2]=4;
gotor[1][3]=6;
gotor[1][4]=15;
gotor[11][4]=14;

/* add,sub,mul,div */
gotor[1][5]=16;
gotor[11][5]=16;
gotor[19][5]=23;
gotor[20][5]=24;
gotor[21][5]=25;
gotor[22][5]=26;

gotor[27][5]=28;

gotor[1][6]=31;
gotor[33][5]=16;
gotor[35][6]=36;

/* *conflict if **** */
gotor[35][4]=60;
/*  ***** */
gotor[37][5]=38;
gotor[39][5]=40;

gotor[41][7]=42;
gotor[42][4]=45;
gotor[41][3]=6;
gotor[41][2]=4;
gotor[41][1]=3;

production[1].len=1;
strcpy(production[1].lhs,"S");
strcpy(production[1].rhs[1].rprod,"decn");

production[2].len=2;
strcpy(production[2].lhs,"decn");
strcpy(production[2].rhs[1].rprod,"var");
strcpy(production[2].rhs[2].rprod,";");

production[3].len=2;
strcpy(production[3].lhs,"var");
strcpy(production[3].rhs[1].rprod,"dt");
strcpy(production[3].rhs[2].rprod,"IDEN");

production[4].len=1;
strcpy(production[4].lhs,"dt");
strcpy(production[4].rhs[1].rprod,"INT");

production[5].len=1;
strcpy(production[5].lhs,"dt");
strcpy(production[5].rhs[1].rprod,"FLOAT");

production[6].len=1;
strcpy(production[6].lhs,"S");
strcpy(production[6].rhs[1].rprod,"assn");

production[7].len=3;
strcpy(production[7].lhs,"assn");
strcpy(production[7].rhs[1].rprod,"IDEN");
strcpy(production[7].rhs[2].rprod,"=");
strcpy(production[7].rhs[3].rprod,"assn");

/*production[8].len=2;
strcpy(production[8].lhs,"assn");
strcpy(production[8].rhs[1].rprod,"CON");
strcpy(production[8].rhs[2].rprod,";");*/

production[9].len=2;
strcpy(production[9].lhs,"assn");
strcpy(production[9].rhs[1].rprod,"exp");
strcpy(production[9].rhs[2].rprod,";");

production[10].len=3;
strcpy(production[10].lhs,"exp");
strcpy(production[10].rhs[1].rprod,"exp");
strcpy(production[10].rhs[2].rprod,"+");
strcpy(production[10].rhs[3].rprod,"exp");

production[11].len=3;
strcpy(production[11].lhs,"exp");
strcpy(production[11].rhs[1].rprod,"exp");
strcpy(production[11].rhs[2].rprod,"-");
strcpy(production[11].rhs[3].rprod,"exp");

production[12].len=3;
strcpy(production[12].lhs,"exp");
strcpy(production[12].rhs[1].rprod,"exp");
strcpy(production[12].rhs[2].rprod,"*");
strcpy(production[12].rhs[3].rprod,"exp");

production[13].len=3;
strcpy(production[13].lhs,"exp");
strcpy(production[13].rhs[1].rprod,"exp");
strcpy(production[13].rhs[2].rprod,"/");
strcpy(production[13].rhs[3].rprod,"exp");

/*production[10].len=3;
strcpy(production[10].lhs,"temp");
strcpy(production[10].rhs[1].rprod,"exp1");
strcpy(production[10].rhs[2].rprod,"+");
strcpy(production[10].rhs[3].rprod,"exp1");

production[11].len=3;
strcpy(production[11].lhs,"temp");
strcpy(production[11].rhs[1].rprod,"exp1");
strcpy(production[11].rhs[2].rprod,"-");
strcpy(production[11].rhs[3].rprod,"exp1");*/

production[14].len=3;
strcpy(production[14].lhs,"exp");
strcpy(production[14].rhs[1].rprod,"(");
strcpy(production[14].rhs[2].rprod,"exp");
strcpy(production[14].rhs[3].rprod,")");

production[15].len=1;
strcpy(production[15].lhs,"exp");
strcpy(production[15].rhs[1].rprod,"CON");

production[16].len=1;
strcpy(production[16].lhs,"exp");
strcpy(production[16].rhs[1].rprod,"IDEN");

production[17].len=1;
strcpy(production[17].lhs,"S");
strcpy(production[17].rhs[1].rprod,"sel");

production[18].len=5;
strcpy(production[18].lhs,"sel");
strcpy(production[18].rhs[1].rprod,"IF");
strcpy(production[18].rhs[2].rprod,"(");
strcpy(production[18].rhs[3].rprod,"exp");
strcpy(production[18].rhs[4].rprod,")");
strcpy(production[18].rhs[5].rprod,"S");

production[19].len=3;
strcpy(production[19].lhs,"exp");
strcpy(production[19].rhs[1].rprod,"exp");
strcpy(production[19].rhs[2].rprod,"&&");
strcpy(production[19].rhs[3].rprod,"exp");

production[20].len=3;
strcpy(production[20].lhs,"exp");
strcpy(production[20].rhs[1].rprod,"exp");
strcpy(production[20].rhs[2].rprod,"||");
strcpy(production[20].rhs[3].rprod,"exp");

production[21].len=5;
strcpy(production[18].lhs,"sel");
strcpy(production[18].rhs[1].rprod,"IF");
strcpy(production[18].rhs[2].rprod,"(");
strcpy(production[18].rhs[3].rprod,"exp");
strcpy(production[18].rhs[4].rprod,")");
strcpy(production[18].rhs[5].rprod,"exp");

production[22].len=3;
strcpy(production[22].lhs,"S");
strcpy(production[22].rhs[1].rprod,"{");
strcpy(production[22].rhs[2].rprod,"p");
strcpy(production[22].rhs[3].rprod,"}");

production[23].len=3;
strcpy(production[23].lhs,"S");
strcpy(production[23].rhs[1].rprod,"{");
strcpy(production[23].rhs[2].rprod,"S");
strcpy(production[23].rhs[3].rprod,"}");

production[24].len=2;
strcpy(production[24].lhs,"S");
strcpy(production[24].rhs[1].rprod,"S");
strcpy(production[24].rhs[2].rprod,"decn");

production[25].len=2;
strcpy(production[25].lhs,"S");
strcpy(production[25].rhs[1].rprod,"S");
strcpy(production[25].rhs[2].rprod,"assn");

production[26].len=2;
strcpy(production[26].lhs,"S");
strcpy(production[26].rhs[1].rprod,"S");
strcpy(production[26].rhs[2].rprod,"S");

production[27].len=3;
strcpy(production[27].lhs,"exp");
strcpy(production[27].rhs[1].rprod,"exp");
strcpy(production[27].rhs[2].rprod,"COMP");
strcpy(production[27].rhs[3].rprod,"exp");

production[28].len=3;
strcpy(production[28].lhs,"exp");
strcpy(production[28].rhs[1].rprod,"exp");
strcpy(production[28].rhs[2].rprod,"ENQ");
strcpy(production[28].rhs[3].rprod,"exp");

production[29].len=1;
strcpy(production[29].lhs,"S");
strcpy(production[29].rhs[1].rprod,"wloop");

production[30].len=5;
strcpy(production[30].lhs,"wloop");
strcpy(production[30].rhs[1].rprod,"WHILE");
strcpy(production[30].rhs[2].rprod,"(");
strcpy(production[30].rhs[3].rprod,"exp");
strcpy(production[30].rhs[4].rprod,")");
strcpy(production[30].rhs[5].rprod,"S");

production[31].len=7;
strcpy(production[31].lhs,"S");
strcpy(production[31].rhs[1].rprod,"FOR");
strcpy(production[31].rhs[2].rprod,"(");
strcpy(production[31].rhs[3].rprod,"S");
//strcpy(production[31].rhs[4].rprod,";");
strcpy(production[31].rhs[4].rprod,"S");
//strcpy(production[31].rhs[6].rprod,";");
strcpy(production[31].rhs[5].rprod,"incr");
strcpy(production[31].rhs[6].rprod,")");
strcpy(production[31].rhs[7].rprod,"S");

production[32].len=3;
strcpy(production[32].lhs,"incr");
strcpy(production[32].rhs[1].rprod,"IDEN");
strcpy(production[32].rhs[2].rprod,"=");
strcpy(production[32].rhs[3].rprod,"exp");


//start recursion


//basic
action[1][1].sr = 'S';
action[1][1].srnum=8;

action[1][2].sr = 'S';
action[1][2].srnum=9;

action[2][4].sr = 'A';
action[2][4].srnum=-1;

action[4][3].sr = 'S';
action[4][3].srnum=5;

action[6][0].sr = 'S';
action[6][0].srnum=7;

action[3][4].sr = 'R';
action[3][4].srnum=1;

action[3][0].sr = 'R';
action[3][0].srnum=1;

action[5][4].sr = 'R';
action[5][4].srnum=2;

action[5][0].sr = 'R';
action[5][0].srnum=2;

action[7][3].sr = 'R';
action[7][3].srnum=3;

action[8][0].sr = 'R';
action[8][0].srnum=4;

action[9][0].sr = 'R';
action[9][0].srnum=5;

action[1][0].sr = 'S';
action[1][0].srnum=10;

action[11][0].sr = 'S';
action[11][0].srnum=10;

action[10][6].sr = 'S';
action[10][6].srnum=11;

action[10][3].sr = 'R';
action[10][3].srnum=16;

action[15][4].sr = 'R';
action[15][4].srnum=6;

action[14][4].sr = 'R';
action[14][4].srnum=7;

action[11][5].sr = 'S';
action[11][5].srnum=17;

action[16][3].sr='S';
action[16][3].srnum=30;

action[30][4].sr='R';
action[30][4].srnum=9;
   
action[1][5].sr = 'S';
action[1][5].srnum=17;

action[17][3].sr='R';
action[17][3].srnum=15;

/*addition*/

action[16][6].sr = 'R';
action[16][6].srnum=9;

action[16][7].sr = 'S';
action[16][7].srnum=19;

action[19][5].sr = 'S';
action[19][5].srnum=17;
    
action[19][0].sr = 'S';
action[19][0].srnum=10;
    
action[23][3].sr = 'R';
action[23][3].srnum=10;

action[23][12].sr = 'R';
action[23][12].srnum=10;

action[23][7].sr = 'R';
action[23][7].srnum=10;

action[23][8].sr = 'R';
action[23][8].srnum=10;

action[23][9].sr = 'S';
action[23][9].srnum=21;

action[23][10].sr = 'S';
action[23][10].srnum=22; 

action[23][14].sr = 'R';
action[23][14].srnum=10; 

action[23][15].sr = 'R';
action[23][15].srnum=10; 

action[10][7].sr = 'R';
action[10][7].srnum=16;

action[17][7].sr = 'R';
action[17][7].srnum=15;

/*subtraction*/
action[16][8].sr = 'S';
action[16][8].srnum=20;

action[20][0].sr = 'S';
action[20][0].srnum=10;

action[20][5].sr = 'S';
action[20][5].srnum=17;

action[10][8].sr = 'R';
action[10][8].srnum=16;

action[17][8].sr = 'R';
action[17][8].srnum=15;

action[24][3].sr = 'R';
action[24][3].srnum=11;

action[24][12].sr = 'R';
action[24][12].srnum=11;

action[24][7].sr = 'R';
action[24][7].srnum=11;

action[24][8].sr = 'R';
action[24][8].srnum=11;

action[24][9].sr = 'R';
action[24][9].srnum=11;

action[24][10].sr = 'R';
action[24][10].srnum=11;

/*multiplication*/
action[16][9].sr = 'S';
action[16][9].srnum=21;

action[21][0].sr = 'S';
action[21][0].srnum=10;

action[21][5].sr = 'S';
action[21][5].srnum=17;

action[10][9].sr = 'R';
action[10][9].srnum=16;

action[17][9].sr = 'R';
action[17][9].srnum=15;

action[25][3].sr = 'R';
action[25][3].srnum=12;

action[25][12].sr = 'R';
action[25][12].srnum=12;

action[25][7].sr = 'R';
action[25][7].srnum=12;

action[25][8].sr = 'R';
action[25][8].srnum=12;

action[25][9].sr = 'R';
action[25][9].srnum=12;

action[25][10].sr = 'R';
action[25][10].srnum=12;

/* division*/
action[16][10].sr = 'S';
action[16][10].srnum=22;

action[22][0].sr = 'S';
action[22][0].srnum=10;

action[22][5].sr = 'S';
action[22][5].srnum=17;

action[10][10].sr = 'R';
action[10][10].srnum=16;

action[17][10].sr = 'R';
action[17][10].srnum=15;

action[26][3].sr = 'R';
action[26][3].srnum=13;

action[26][12].sr = 'R';
action[26][12].srnum=13;

action[26][7].sr = 'R';
action[26][7].srnum=13;

action[26][8].sr = 'R';
action[26][8].srnum=13;

action[26][9].sr = 'R';
action[26][9].srnum=13;

action[26][10].sr = 'R';
action[26][10].srnum=13;

//logical and
action[16][14].sr = 'S';
action[16][14].srnum=37;

action[28][14].sr = 'S';
action[28][14].srnum=37;

action[37][0].sr = 'S';
action[37][0].srnum=10;

action[37][5].sr = 'S';
action[37][5].srnum=17;

action[37][11].sr = 'S';
action[37][11].srnum=27;

action[10][14].sr = 'R';
action[10][14].srnum=16;

action[17][14].sr = 'R';
action[17][14].srnum=15;

action[38][3].sr = 'R';
action[38][3].srnum=19;

action[38][12].sr = 'R';
action[38][12].srnum=19;

action[38][14].sr = 'R';
action[38][14].srnum=19;

action[38][15].sr = 'R';
action[38][15].srnum=19;

action[38][7].sr = 'S';
action[38][7].srnum=19;

action[38][8].sr = 'S';
action[38][8].srnum=20;

action[38][9].sr = 'S';
action[38][9].srnum=21;

action[38][10].sr = 'S';
action[38][10].srnum=22;

//logical or

action[16][15].sr = 'S';
action[16][15].srnum=39;

action[28][15].sr = 'S';
action[28][15].srnum=39;

action[39][0].sr = 'S';
action[39][0].srnum=10;

action[39][5].sr = 'S';
action[39][5].srnum=17;

action[39][11].sr = 'S';
action[39][11].srnum=27;

action[10][15].sr = 'R';
action[10][15].srnum=16;

action[17][15].sr = 'R';
action[17][15].srnum=15;

action[40][3].sr = 'R';
action[40][3].srnum=20;

action[40][12].sr = 'R';
action[40][12].srnum=20;

action[40][14].sr = 'R';
action[40][14].srnum=20;

action[40][15].sr = 'R';
action[40][15].srnum=20;

action[40][7].sr = 'S';
action[40][7].srnum=19;

action[40][8].sr = 'S';
action[40][8].srnum=20;

action[40][9].sr = 'S';
action[40][9].srnum=21;

action[40][10].sr = 'S';
action[40][10].srnum=22;

/*parenthesis*/
action[1][11].sr = 'S';
action[1][11].srnum=27;

action[27][11].sr = 'S';
action[27][11].srnum=27;

action[27][0].sr = 'S';
action[27][0].srnum=10;

action[27][5].sr = 'S';
action[27][5].srnum=17;

action[19][11].sr = 'S';
action[19][11].srnum=27;

action[20][11].sr = 'S';
action[20][11].srnum=27;

action[21][11].sr = 'S';
action[21][11].srnum=27;

action[22][11].sr = 'S';
action[22][11].srnum=27;

action[28][7].sr = 'S';
action[28][7].srnum=19;

action[28][8].sr = 'S';
action[28][8].srnum=20;

action[28][9].sr = 'S';
action[28][9].srnum=21;

action[28][10].sr = 'S';
action[28][10].srnum=22;

action[28][12].sr = 'S';
action[28][12].srnum=29;

action[11][11].sr = 'S';
action[11][11].srnum=27;

action[29][3].sr = 'R';
action[29][3].srnum=14;

action[29][12].sr = 'R';
action[29][12].srnum=14;

action[29][9].sr = 'R';
action[29][9].srnum=14;

action[29][10].sr = 'R';
action[29][10].srnum=14;

action[29][7].sr = 'R';
action[29][7].srnum=14;

action[29][8].sr = 'R';
action[29][8].srnum=14;

action[29][6].sr = 'R';
action[29][6].srnum=14;

action[29][14].sr = 'R';
action[29][14].srnum=14;

action[29][15].sr = 'R';
action[29][15].srnum=14;

action[10][12].sr = 'R';
action[10][12].srnum=16;

action[17][12].sr = 'R';
action[17][12].srnum=15;

//if statement

action[31][4].sr = 'R';
action[31][4].srnum=17;

action[1][13].sr = 'S';
action[1][13].srnum=32;

action[32][11].sr='S';
action[32][11].srnum=33;

action[16][12].sr='S';
action[16][12].srnum=35;

action[33][5].sr='S';
action[33][5].srnum=16;

action[33][11].sr='S';
action[33][11].srnum=27;

action[33][5].sr='S';
action[33][5].srnum=17;

action[35][0].sr='S';
action[35][0].srnum=10;

action[33][0].sr='S';
action[33][0].srnum=10;

action[36][4].sr = 'R';
action[36][4].srnum=21;

action[35][13].sr = 'S';
action[35][13].srnum=32;

action[60][4].sr = 'R';
action[60][4].srnum=6;

//action[37][0].sr = 'R';
//action[37][0].srnum=6;

//action[37][1].sr = 'R';
//action[37][1].srnum=6;

//action[37][2].sr = 'R';
//action[37][2].srnum=6;

action[48][4].sr = 'R';
action[48][4].srnum=18;

action[48][0].sr = 'S';
action[48][0].srnum=10;

action[35][16].sr = 'S';
action[35][16].srnum=41;

//recursion decn

action[46][4].sr='R';
action[46][4].srnum=24;

action[46][0].sr='R';
action[46][0].srnum=24;

action[46][1].sr='R';
action[46][1].srnum=24;

action[46][2].sr='R';
action[46][2].srnum=24;

action[46][20].sr='R';
action[46][20].srnum=24;

action[46][21].sr='R';
action[46][21].srnum=24;

action[5][1].sr = 'R';
action[5][1].srnum=2;

action[3][1].sr = 'R';
action[3][1].srnum=1;

action[2][1].sr = 'S';
action[2][1].srnum=8;

action[5][2].sr = 'R';
action[5][2].srnum=2;

action[3][2].sr = 'R';
action[3][2].srnum=1;

action[2][2].sr = 'S';
action[2][2].srnum=8;

//recursion assn

action[47][4].sr='R';
action[47][4].srnum=25;

action[47][0].sr='R';
action[47][0].srnum=25;

action[47][1].sr='R';
action[47][1].srnum=25;

action[47][2].sr='R';
action[47][2].srnum=25;

action[47][21].sr='R';
action[47][21].srnum=25;

action[2][0].sr = 'S';
action[2][0].srnum=10;

action[30][0].sr = 'R';
action[30][0].srnum=9;

action[14][0].sr = 'R';
action[14][0].srnum=7;

action[14][1].sr = 'R';
action[14][1].srnum=7;

action[14][2].sr = 'R';
action[14][2].srnum=7;

action[15][0].sr = 'R';
action[15][0].srnum=6;

action[15][1].sr = 'R';
action[15][1].srnum=6;

action[15][2].sr = 'R';
action[15][2].srnum=6;

action[30][2].sr = 'R';
action[30][2].srnum=9;

action[30][1].sr = 'R';
action[30][1].srnum=9;

//curly brackets

action[1][16].sr = 'S';
action[1][16].srnum=49;

action[49][1].sr = 'S';
action[49][1].srnum=8;

action[49][2].sr = 'S';
action[49][2].srnum=9;

action[49][0].sr = 'S';
action[49][0].srnum=10;

action[5][17].sr = 'R';
action[5][17].srnum=2;

action[3][17].sr = 'R';
action[3][17].srnum=1;

action[3][13].sr = 'R';
action[3][13].srnum=1;

action[51][4].sr = 'R';
action[51][4].srnum=23;

action[46][17].sr = 'R';
action[46][17].srnum=24;

action[2][17].sr = 'S';
action[2][17].srnum=51;

action[30][17].sr = 'R';
action[30][17].srnum=9;

action[14][17].sr = 'R';
action[14][17].srnum=7;

action[15][17].sr = 'R';
action[15][17].srnum=6;

action[47][17].sr = 'R';
action[47][17].srnum=25;

action[41][0].sr = 'S';
action[41][0].srnum=10;

action[41][1].sr = 'S';
action[41][1].srnum=8;

action[41][2].sr = 'S';
action[41][2].srnum=9;

action[41][13].sr = 'S';
action[41][13].srnum=32;

action[37][17].sr = 'R';
action[37][17].srnum=6;

action[48][17].sr = 'R';
action[48][17].srnum=18;

action[31][17].sr = 'R';
action[31][17].srnum=17;

action[51][17].sr = 'R';
action[51][17].srnum=23;

action[30][13].sr = 'R';
action[30][13].srnum=9;

action[14][13].sr = 'R';
action[14][13].srnum=7;

action[15][13].sr = 'R';
action[15][13].srnum=6;

action[2][13].sr = 'S';
action[2][13].srnum=32;

action[52][17].sr = 'R';
action[52][17].srnum=26;

action[47][13].sr = 'R';
action[47][13].srnum=25;

action[5][13].sr = 'R';
action[5][13].srnum=2;

action[5][13].sr = 'R';
action[5][13].srnum=2;

action[46][13].sr = 'R';
action[46][13].srnum=24;

action[51][0].sr = 'R';
action[51][0].srnum=23;

action[48][1].sr = 'R';
action[48][1].srnum=18;

action[48][2].sr = 'R';
action[48][2].srnum=23;

action[51][1].sr = 'R';
action[51][1].srnum=23;

action[51][2].sr = 'R';
action[51][2].srnum=23;

action[52][1].sr = 'R';
action[52][1].srnum=26;

action[52][2].sr = 'R';
action[52][2].srnum=26;

action[37][13].sr = 'R';
action[37][13].srnum=6;

action[48][13].sr = 'R';
action[48][13].srnum=18;

action[31][13].sr = 'R';
action[31][13].srnum=17;

action[52][4].sr = 'R';
action[52][4].srnum=26;

//comparison operators
action[10][18].sr = 'R';
action[10][18].srnum=16;

action[17][18].sr = 'R';
action[17][18].srnum=15;

action[16][18].sr = 'S';
action[16][18].srnum=53;

action[53][0].sr = 'S';
action[53][0].srnum=10;

action[53][5].sr = 'S';
action[53][5].srnum=17;

action[54][3].sr = 'R';
action[54][3].srnum=27;

action[54][14].sr = 'R';
action[54][14].srnum=27;

action[54][15].sr = 'R';
action[54][15].srnum=27;

action[54][18].sr = 'R';
action[54][18].srnum=27;

action[54][12].sr = 'R';
action[54][12].srnum=27;

action[54][7].sr = 'S';
action[54][7].srnum=19;

action[54][8].sr = 'S';
action[54][8].srnum=20;

action[54][9].sr = 'S';
action[54][9].srnum=21;

action[54][10].sr = 'S';
action[54][10].srnum=22;

action[28][18].sr = 'S';
action[28][18].srnum=53;

action[29][18].sr = 'R';
action[29][18].srnum=14;

//equal and not equal
action[10][19].sr = 'R';
action[10][19].srnum=16;

action[17][19].sr = 'R';
action[17][19].srnum=15;

action[16][19].sr = 'S';
action[16][19].srnum=55;

action[55][0].sr = 'S';
action[55][0].srnum=10;

action[55][5].sr = 'S';
action[55][5].srnum=17;

action[56][3].sr = 'R';
action[56][3].srnum=28;

action[56][12].sr = 'R';
action[56][12].srnum=28;

action[56][15].sr = 'R';
action[56][15].srnum=28;

action[56][14].sr = 'R';
action[56][14].srnum=28;

action[56][19].sr = 'R';
action[56][19].srnum=28;

//while loop
action[1][20].sr = 'S';
action[1][20].srnum=61;

action[61][11].sr='S';
action[61][11].srnum=62;

action[62][0].sr='S';
action[62][0].srnum=10;

action[63][12].sr='S';
action[63][12].srnum=64;

action[64][0].sr='S';
action[64][0].srnum=10;

action[62][5].sr='S';
action[62][5].srnum=17;

action[65][4].sr='R';
action[65][4].srnum=6;

action[66][4].sr='R';
action[66][4].srnum=30;

action[67][4].sr='R';
action[67][4].srnum=29;

action[35][20].sr = 'S';
action[35][20].srnum=61;

action[30][20].sr = 'R';
action[30][20].srnum=9;

action[14][20].sr = 'R';
action[14][20].srnum=7;

action[15][20].sr = 'R';
action[15][20].srnum=6;

action[2][20].sr = 'S';
action[2][20].srnum=61;

action[60][17].sr = 'R';
action[60][17].srnum=6;
    
//for loop
action[1][21].sr = 'S';
action[1][21].srnum=70;

action[70][11].sr = 'S';
action[70][11].srnum=71;

action[71][0].sr = 'S';
action[71][0].srnum=10;

action[72][0].sr = 'S';
action[72][0].srnum=10;

action[73][0].sr = 'S';
action[73][0].srnum=74;

action[74][6].sr = 'S';
action[74][6].srnum=75;
    
action[75][5].sr = 'S';
action[75][5].srnum=76;

action[75][0].sr = 'S';
action[75][0].srnum=76;

action[76][12].sr = 'R';
action[76][12].srnum=15;

action[77][12].sr = 'R';
action[77][12].srnum=32;

action[78][12].sr = 'S';
action[78][12].srnum=79;

action[79][0].sr = 'S';
action[79][0].srnum=10;

action[80][4].sr = 'R';
action[80][4].srnum=31;

action[76][7].sr = 'S';
action[76][7].srnum=81;

action[76][8].sr = 'S';
action[76][8].srnum=81;

action[81][5].sr = 'S';
action[81][5].srnum=82;

action[81][0].sr = 'S';
action[81][0].srnum=82;

action[82][12].sr = 'R';
action[82][12].srnum=10;

action[79][16].sr = 'S';
action[79][16].srnum=49;

action[49][21].sr = 'S';
action[49][21].srnum=70;

action[80][17].sr = 'R';
action[80][17].srnum=31;

action[30][21].sr = 'R';
action[30][21].srnum=9;

action[14][21].sr = 'R';
action[14][21].srnum=7;

action[15][21].sr = 'R';
action[15][21].srnum=6;

action[2][21].sr = 'S';
action[2][21].srnum=70;

action[51][21].sr = 'R';
action[51][21].srnum=23;

action[48][21].sr = 'R';
action[48][21].srnum=18;

action[52][21].sr = 'R';
action[52][21].srnum=26;

//action[2][21].sr = 'R';
//action[2][21].srnum=26;

action[51][13].sr = 'R';
action[51][13].srnum=23;

action[52][13].sr = 'R';
action[52][13].srnum=26;

action[60][13].sr = 'R';
action[60][13].srnum=6;

action[60][21].sr = 'R';
action[60][21].srnum=6;

action[80][21].sr = 'R';
action[80][21].srnum=31;

action[49][13].sr = 'S';
action[49][13].srnum=32;

action[41][21].sr = 'S';
action[41][21].srnum=70;

action[31][21].sr = 'R';
action[31][21].srnum=17;

action[47][20].sr = 'R';
action[47][20].srnum=25;

action[51][20].sr = 'R';
action[51][20].srnum=23;

action[48][20].sr = 'R';
action[48][20].srnum=18;

action[52][20].sr = 'R';
action[52][20].srnum=26;

action[5][20].sr = 'R';
action[5][20].srnum=2;

action[3][20].sr = 'R';
action[3][20].srnum=1;

action[41][20].sr = 'S';
action[41][20].srnum=32;

action[5][21].sr = 'R';
action[5][21].srnum=2;

action[60][0].sr = 'R';
action[60][0].srnum=6;


    char act;
    int g;
    int iteration=1;
   int length;
   int i;
    int going;
   FILE* fl=fopen("logfile.txt","a");   
   
   yyin=fopen("inout.c","r"); 
   
   stacks[++stackstop]=1;
   ink=yylex();
   

   
   while(1)
   {     
      fprintf(fl,"\nITERATION %d\n",iteration); iteration++;
       
	loo: 
       if(ink==1) index=0;
       else if(ink==2) index=1;
       else if(ink==3) index=2;
       else if(ink==4) index=3;
       else if(ink==5) index=4;
       else if(ink==6) index=5;
       else if(ink==7) index=6;
       else if(ink==8) index=7;
       else if(ink==9) index=8;
       else if(ink==10) index=9;
       else if(ink==11) index=10;
       else if(ink==12) index=11;
       else if(ink==13) index=12;
       else if(ink==14) index=13;
       else if(ink==15) index=14;
       else if(ink==16) index=15;
       else if(ink==17) index=16;
       else if(ink==18) index=17;
       else if(ink==19) index=18;
       else if(ink==20) index=19;
       else if(ink==21) index=20;
       else if(ink==22) index=21;
     
      act=action[stacks[stackstop]][index].sr;
      
   
      g=action[stacks[stackstop]][index].srnum;
    //  printf("%d, %d\n",stacks[stackstop],index);
    
      if(g==0) 
	  {
	  	//printf(" %d",stacks[stackstop]);
	    recover();  continue;
	   // break;
     }
	if(act=='A')
        {
          if(stackstop==1)
         {
          //printf("accepted %d",stacks[stackstop]) ;
	  break; 
         }
 
         else 
            {recover(); ink=yylex(); 
               continue;
                 //break;
             }

        }    
      
    else if(act=='S')
    {  
       int l;
      symbolstop++;
      if(index==0)strcpy(symbols[symbolstop].ss,"IDEN");
      if(index==1)strcpy(symbols[symbolstop].ss,"INT");
      if(index==2)strcpy(symbols[symbolstop].ss,"FLOAT");
      if(index==3)strcpy(symbols[symbolstop].ss,";");
      if(index==4)strcpy(symbols[symbolstop].ss,"$");
      if(index==5)strcpy(symbols[symbolstop].ss,"CON");
      if(index==6)strcpy(symbols[symbolstop].ss,"=");
      if(index==7)strcpy(symbols[symbolstop].ss,"+");
      if(index==8)strcpy(symbols[symbolstop].ss,"-");
      if(index==9)strcpy(symbols[symbolstop].ss,"*");
      if(index==10)strcpy(symbols[symbolstop].ss,"/");
      if(index==11)strcpy(symbols[symbolstop].ss,"(");
      if(index==12)strcpy(symbols[symbolstop].ss,")");
      if(index==13)strcpy(symbols[symbolstop].ss,"IF");
      if(index==14)strcpy(symbols[symbolstop].ss,"&&");
      if(index==15)strcpy(symbols[symbolstop].ss,"||");
      if(index==16)strcpy(symbols[symbolstop].ss,"{");
      if(index==17)strcpy(symbols[symbolstop].ss,"}");
      if(index==18)strcpy(symbols[symbolstop].ss,"COMP");
      if(index==19)strcpy(symbols[symbolstop].ss,"ENQ");
      if(index==20)strcpy(symbols[symbolstop].ss,"WHILE");
      if(index==21)strcpy(symbols[symbolstop].ss,"FOR");

      stacks[++stackstop]=g;
     // printf("action: %d\n",g);       
     
     
     
       fprintf(fl,"\n\n");
      for(l=0;l<=symbolstop;l++)
       fprintf(fl,"symbol %s\n",symbols[l].ss);
      
   
   
       int m;
       fprintf(fl,"\n\n");
      for(m=0;m<=stackstop;m++)
       fprintf(fl,"stacks %d\n",stacks[m]);
      
      fprintf(fl,"action: S %d\n",g); 
    
     ink=yylex();
    
    
    }
  else if(act=='R')
    {   
    	
        int l;
        int m;
        length=production[g].len;
       
	   stackstop=stackstop-length;
	   symbolstop=symbolstop-length;
	   
	   	if(strcmp(production[g].lhs,"S")==0) index1=0;
		if(strcmp(production[g].lhs,"decn")==0) index1=1;
                if(strcmp(production[g].lhs,"var")==0) index1=2;
		if(strcmp(production[g].lhs,"dt")==0) index1=3;
                if(strcmp(production[g].lhs,"assn")==0) index1=4;
                if(strcmp(production[g].lhs,"exp")==0) index1=5;
                if(strcmp(production[g].lhs,"sel")==0) index1=6;
                if(strcmp(production[g].lhs,"wloop")==0) index1=7;
                if(strcmp(production[g].lhs,"incr")==0) index1=8;
              

	    else ;
	    
	         symbolstop++;
	     	 strcpy(symbols[symbolstop].ss,production[g].lhs);
	     
		 
	
	
	going=gotor[stacks[stackstop]][index1];
	stacks[++stackstop]=going;
         
        fprintf(fl,"\n\n");
	 for(l=0;l<=symbolstop;l++)
       fprintf(fl,"symbol %s\n",symbols[l].ss);

        fprintf(fl,"\n\n");
      for(m=0;m<=stackstop;m++)
       fprintf(fl,"stacks %d\n",stacks[m]); 
  
      fprintf(fl,"action: R %d\n",g);
     
  }
	
   if(stackstop==-1 || symbolstop==-1)break;
   	
	
}

if(act=='A' && stackstop==1) {if(errors==0)printf("\nsyntactically correct\n");}

}


void recover()
{ int l,m; ++errors; char a[10];
printf("rejected\n");

 if(strcmp(symbols[symbolstop].ss,"S")==0 || stacks[stackstop]==49)
  {printf("error on line %d: missing }\n", lines); 
    strcpy(symbols[++symbolstop].ss,"}");
    stacks[++stackstop]=51;
  }

 else if(stacks[stackstop]==28)
  {printf("error on line %d: missing ) in expression\n",lines);
   strcpy(symbols[++symbolstop].ss,")");
    stacks[++stackstop]=29;
 }

 else if(strcmp(symbols[symbolstop].ss,"=")==0)
   {printf("error on line %d: missing expression\n",lines);
     strcpy(symbols[++symbolstop].ss,"IDEN");
     stacks[++stackstop]=10;
    }

 else if(stacks[stackstop]==19 || stacks[stackstop]==20 || stacks[stackstop]==21 ||stacks[stackstop]==22 || stacks[stackstop]==37 )
   {printf("error on line %d: missing operand\n",lines);
     strcpy(symbols[++symbolstop].ss,"IDEN");
     stacks[++stackstop]=10;
   }

 else if(strcmp(symbols[symbolstop].ss,"}")==0 || stacks[stackstop]==51)
  {printf("error on line %d: extra }\n", lines); 
     exit(0);
  }
 
 /* else if(stacks[stackstop]==28)
  {printf("error on line %d: missing ) in expression\n",lines);
   strcpy(symbols[++symbolstop].ss,")"); 
    //stacks[++stackstop]=29;
 }*/

 /*else if(stacks[stackstop]==7)
  {printf("error on line %d: missing ; in expression\n",lines);
   strcpy(symbols[++symbolstop].ss,";"); ink=yylex();
    //stacks[++stackstop]=29;
 }*/

else if(stacks[stackstop]==10)
  {printf("error on line %d: missing ; in expression\n",lines);
    while(stacks[stackstop]!=49){stackstop--;symbolstop--;} 
    //stacks[++stackstop]=29;
 
 }
  else exit(0);
}


int value()
{
int i;
int flag=0;
if(sttop==-1)
{
 strcpy(symboltable[++sttop].sm,(char *)yytext);
 //printf("%s",symboltable[sttop].sm);
 return 1;
}

else
{
for(i=0;i<=sttop;i++)
 {
 if(strcmp(yytext,symboltable[i].sm)==0)
   { flag=1;}
 } 
 if(flag==0 &&(strcmp(symbols[symbolstop].ss,"INT")==0 || strcmp(symbols[symbolstop].ss,"FLOAT")==0))
{
 strcpy(symboltable[++sttop].sm,(char *)yytext);
 //printf("%s",symboltable[sttop].sm);
 return 1;
}
else if(flag==1 &&(strcmp(symbols[symbolstop].ss,"INT")==0 || strcmp(symbols[symbolstop].ss,"FLOAT")==0))
 { printf("\nline %d:variable %s redeclared\n",lines,yytext); errors++;
   return 1; 
 }
else if(flag==0)
 {
   printf("\nline %d:variable %s undeclared\n",lines,yytext); errors++;
   return 1; 
 }
}
return 1;
}
yywrap()
{
 }